version: "3"
services:
  jupiter:
    container_name: jupiter
    image: notebook
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ./:/opt/
    command: "jupyter notebook --allow-root --ip='0.0.0.0' --port=8888 --no-browser"
